language: go
go:
 - 1.x
 - tip

before_install:
 - go get github.com/kardianos/govendor
 - go get github.com/mattn/goveralls

script:
 - govendor sync
 - go test -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN